name       : haskell-socks
version    : 0.5.6
release    : 2
source     :
    - https://hackage.haskell.org/package/socks-0.5.6/socks-0.5.6.tar.gz : fa63cd838025e18864c59755750c0cfc4ea76e140a542f07a5c682488ec78438
license    : BSD-3-Clause
component  : programming.haskell
summary    : Socks proxy (version 5) implementation.
description: Socks proxy (version 5) implementation.
builddeps  :
    - haskell-cabal-install
    - haskell-cereal
    - haskell-network
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
