name       : haskell-socks
version    : 0.5.5
release    : 1
source     :
    - http://hackage.haskell.org/package/socks-0.5.5/socks-0.5.5.tar.gz : 2647ea93e21ad1dfd77e942c022c8707e468d25e1ff672a88be82508034fc868
license    : BSD-3-Clause
component  : programming.haskell
summary    : Socks proxy (version 5) implementation. 
description: |
    Socks proxy (version 5) implementation. 
builddeps  :
    - haskell-cabal-install
    - haskell-cereal
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
