name       : haskell-socks
version    : 0.6.1
release    : 3
source     :
    - https://hackage.haskell.org/package/socks-0.6.1/socks-0.6.1.tar.gz : 734447558bb061ce768f53a0df1f2401902c6bee396cc96ce627edd986ef6a73
license    : BSD-3-Clause
component  : programming.haskell
summary    : Socks proxy (version 5) implementation.
description: |
    Socks proxy (version 5) implementation.
builddeps  :
    - haskell-basement-devel
    - haskell-cabal-install
    - haskell-cereal-devel
    - haskell-network-devel
rundeps    :
    - devel:
        - haskell-basement-devel
        - haskell-cereal-devel
        - haskell-network-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
